name: gcp-terraform-plan

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment workspace (dev|stage|prod)"
        required: true
        default: "dev"

jobs:
  plan:
    if: ${{ vars.GCP_WIF_PROVIDER != '' && vars.GCP_WIF_SERVICE_ACCOUNT != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      TF_DIR: infra/gcp/cloud_run_demo
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      REGION: ${{ vars.REGION }}
      TFSTATE_BUCKET: ${{ vars.TFSTATE_BUCKET }}
      TFSTATE_PREFIX: ${{ vars.TFSTATE_PREFIX }}

      TF_VAR_project_id: ${{ vars.PROJECT_ID }}
      TF_VAR_region: ${{ vars.REGION }}
      TF_VAR_env: ${{ inputs.env }}
      TF_VAR_service_name: "gkp-${{ inputs.env }}"
      TF_VAR_image: ${{ vars.IMAGE }}
      TF_VAR_workspace_domain: ${{ vars.WORKSPACE_DOMAIN }}
      TF_VAR_group_prefix: ${{ vars.GROUP_PREFIX }}
      TF_VAR_enable_project_iam: ${{ vars.ENABLE_PROJECT_IAM }}


    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform init (remote state)
        run: |
          terraform -chdir=${{ env.TF_DIR }} init -reconfigure             -backend-config="bucket=${{ env.TFSTATE_BUCKET }}"             -backend-config="prefix=${{ env.TFSTATE_PREFIX }}/${{ inputs.env }}"

      - name: Terraform plan
        run: terraform -chdir=${{ env.TF_DIR }} plan -no-color
